### ISSUE TITLE
get_stats19()

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/stats19#11]
See #3

**Comment by layik** [comment]
So this function would:
1. call `dl_stats19` with say accidents then >
2. call `read_accidents`
3. call `format_accidents`

Returns a clean `df` ready to be punched.

**Comment by layik** [comment]
I assume!

**Comment by Robinlovelace** [comment]
Yes and maybe provide some additional things, e.g. allow the user to specify if they want the output to be in an `sf` object.

**Comment by layik** [comment]
I think I have enough to plough ahead. Thanks.

**Comment by layik** [comment]
@Robinlovelace can we shelve this please? There will be lots of ways people would want to "get" stats19. I suggest we let users re-open/reference this issue if they need our help.

**Comment by Robinlovelace** [comment]
Sure - not a priority. Pending feedback from  https://github.com/ropensci/onboarding/issues/266 I'm happy for it to be shelved.

**Comment by layik** [comment]
@Robinlovelace's above comment is a little scary, he predicted it :)

**Comment by layik** [comment]
Awaiting my PR.
