### ISSUE TITLE
refactor dl_ functions

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/stats19#12]
I think the `stats19` in `stats19::dl_stats19_2017_ac()` isn't necessary. Would `dl_2017_ac()` or `dl_2017_accidents()` be better names? @layik I reckon this one is right up your street.

**Comment by layik** [comment]
Above is first step, renaming would probably go under a new strategy, do we add/remove any?

And then name conventions can easily be applied. Looks like `dl_2017_accidents()` will be better/consistent.

**Comment by Robinlovelace** [comment]
Now I see where you're going with `generate_file_name()` function, looks great. Yes `dl_2017_accidents` is clearer so let's go with that. I think it makes sense to keep `accidents`, `casualties` and `vehicles` separate as they are separate tables - I think add as many new functions as are needed to go back to 1974 is a good plan.

**Comment by layik** [comment]
So to be clear, we remove all `stats19` refs from function names except `dl_stats19` @Robinlovelace?

**Comment by Robinlovelace** [comment]
Yes sounds good - `dl_stats19()` can be an easy-to-use wrapper, similar to `get_stats19()` mentioned in #11

**Comment by layik** [comment]
if not acceptable, please reopen.

**Comment by layik** [comment]
I think there was a different thread but this is a good place. @Robinlovelace should we remove all `dl_` "handy" functions and just leave it with the `dl_stats19` which is charged by the `find_file_name`?

**Comment by Robinlovelace** [comment]
I think that's the most consistent way forward. If you're happy with that, please do.

**Comment by layik** [comment]
Yep, makes the :package: :rocket: smart.

**Comment by layik** [comment]
Done for good this time.

**Comment by Robinlovelace** [comment]
🚀
