### ISSUE TITLE
Imrove/cleanup read_stats19.R

### ISSUE THREAD

**Issue by layik** [ITSLeeds/stats19#13]
My suggestion is clear up all `format` functions in `read_stats19.R` and move them (if needed) into `format.R` which sounds like they are not needed anymore? Agree @Robinlovelace and @mem48?

**Comment by Robinlovelace** [comment]
Hey Layik: well spotted. Yes the code in https://github.com/ITSLeeds/stats19/blob/master/R/format.R makes all this code redundant. We can now delete these lines :fireworks:  : https://github.com/ITSLeeds/stats19/blob/master/R/read_stats19.R#L41-L343

**Comment by layik** [comment]
Awesome, self assigning.

**Comment by layik** [comment]
![](https://camo.githubusercontent.com/aeea4aa7861cafa36467c225d88e06130a0beb20/68747470733a2f2f636f6465636f762e696f2f67682f4954534c656564732f737461747331392f6272616e63682f6d61737465722f67726170682f62616467652e737667)

Lets keep it that way and above.
