### ISSUE TITLE
Refactor read_ functions to take filename, directory, type and year arguments

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/stats19#16]
As discussed with @layik I think the arguments should go in that order and be something like:

```r
read_* = function(filename = NULL, data_dir = tempdir(), type = NULL, years = NULL) {

  # ...

}
```

For all 3 read functions now in https://github.com/ITSLeeds/stats19/blob/master/R/read_stats19.R

**Comment by layik** [comment]
OK, I think the first thing to change about the parameters is that we restrict `read_accidents` to `type = "accidents` and likewise for `_vehicles` and `_casualties`.

**Comment by layik** [comment]
```{r}
read_* = function(filename = NULL, data_dir = tempdir(),  years = NULL) {

  # ...

}
```

**Comment by Robinlovelace** [comment]
Aha yes, I forgot about that logical inconsistency. So yes we'll only need 3 args. That previous code chunk suggestion looks spot on 👍

**Comment by layik** [comment]
Thanks @Robinlovelace.

**Comment by Robinlovelace** [comment]
At some point we could merge them all into a single `read_stats19()` but good to develop 'atomic' functions for now. Here's a good example of advocacy for many small function instead of a few ones with many args btw: https://github.com/jblindsay/whitebox-tools#how-does-whiteboxtools-design-philosophy-differ - heads-up @mem48 that's a better articulation of the modularisation philosophy than I could manage!

**Comment by layik** [comment]
Discussing code before writing it, always helps.
