### ISSUE TITLE
Remove/move downloaded .zip file?

### ISSUE THREAD

**Issue by layik** [ITSLeeds/stats19#18]
https://github.com/ITSLeeds/stats19/blob/master/R/utils.R#L213

**Comment by Robinlovelace** [comment]
I think it's OK to stay at the default location in `/tmp/`. An alternative would be to add an argument remove it after the download but I don't think that would be frequently used: some people may want to retain a copy of the data. Please clarify the suggestion and benefits of removing the file (so stats19 zip files don't clog up hard disks I imagine).

**Comment by mpadge** [comment]
Sorry, I hadn't seen this issue. Yeah, @Robinlovelace, I'd suggest it's exactly as you indicate: just to avoid junking up directories. With the exception of the [1974-2004 beast](#22), the `.zip` files are lightweight and can readily be simply deleted. If `R.cache` is used, then this deletion will be no issue whatsoever, as they'll remain cached anyway.

**Comment by layik** [comment]
So just to be clear, we pass in a `data_dir` and downloads would be pointed to the parameter. Not sure if you guys mean we should: (1) keep a copy in current session or (2) go for `R.cache` or (3) clean up these `4.5mb` files.

**Comment by mpadge** [comment]
The caching issue is separate from downloading with / without keeping `.zip` files. This current issue is only about removing the `.zip` after the contents (`.csv` in all cases) have been extracted.

Caching will simply allow repeated calls to `dl_stats19` to run without actually downloading from S3, but the user interface will not change at all and nobody will ever have to see nor care about caching (excepting one additional function, `clear_stats19_cache()` to permit exactly that).

**Comment by layik** [comment]
Thanks Mark, closing this as sounds like we don't have an issue for files after 2004.

**Comment by Robinlovelace** [comment]
Cheers for the clarification. Just to further clarify, @mpadge when you say

 > Caching will simply allow repeated calls to dl_stats19 to run without actually downloading from S3

Does that hold true between different R sessions?

**Comment by mpadge** [comment]
yep
