### ISSUE TITLE
Parse names for stats 1974-2004

### ISSUE THREAD

**Issue by mpadge** [ITSLeeds/stats19#21]
These data appear to exist as "Stats19-Data1979-2004.zip", yet years [1980-2003] will not be `grep`-ed onto file names. These will need to be handled separately, followed by a post-processsing of the results to sub-select only the desired years from that file. I haven't tried this yet because the `zip` file is a 240MB beast, but given that, I presume that this would both work and be necessary.

**Comment by layik** [comment]
Thanks Mark! Too eager to get on with plotting the data on the map and I probably should have started from earliest. Self assigning...

**Comment by mpadge** [comment]
@layik It's a bit more complicated that might seem at first sight - see related issue #22

**Comment by layik** [comment]
```r
> find_file_name(years = 2004)
[1] "MakeModel2004_2008.zip"    "Stats19-Data1979-2004.zip"
> dl_stats19(years = 2004)
More than one file found:
Please corresponding file number: 
[1] MakeModel2004_2008.zip
[2] Stats19-Data1979-2004.zip
1 - 2: 2
File to download:
Stats19-Data1979-2004.zip
Attempt downloading from: 
http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/Stats19-Data1979-2004.zip
happy to go (Y = enter, N = esc)?
trying URL 'http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/Stats19-Data1979-2004.zip'
Content type 'application/x-zip-compressed' length 253669263 bytes (241.9 MB)
==================================================
downloaded 241.9 MB

[1] "Data saved at: /tmp/Rtmpc5Bk8B/Stats19-Data1979-2004/Accidents7904.csv"
[2] "Data saved at: /tmp/Rtmpc5Bk8B/Stats19-Data1979-2004/Casualty7904.csv" 
[3] "Data saved at: /tmp/Rtmpc5Bk8B/Stats19-Data1979-2004/Vehicles7904.csv" 
> dl_stats19(years = 2003)
For parameters: 
[1] "years: 2003"
No results found, please try again
```

**Comment by mpadge** [comment]
Yeah, that's all that I mean. The downstream changes from my PR are actually pretty hefty, because you seem to be mixing `stats19::file_names` with what is actually on disk. This is arguably not a great idea because the contents of some of the target (`.zip`) files differ from the S3 list (2017, for example, just has "Acc.csv" with no year appended at all). I'd suggest your `locate_files` and `locate_one_file` functions actually just use `list.files(data_dir)`, and match to desired `year` and `type` args - much simpler, and failsafe in cases where files have been renamed. 

Two options:
1. Accept my PR, which will break the package, but then one or more of us can more easily fix it up accordingly; or
2. Wait while I do the fixing, but that will involve some considerably rewrites in order to address the above

A further note: I've got local changes which auto-rewrite extracted file names where these don't contain year info (like 2017). I've also got some code to modify local file names for those cases.

**Comment by layik** [comment]
Pushed without having read your comment @mpadge. 
Just reply to the points above:
1. I dont think I am mixing `stats19::file_name` with what is on disk, what we are doing is finding the folders (no `.zip`) and locate files under them.
2. `locate_files` is just a helper function, crucial is `locate_one_file` which takes us to the next level of the package, we would soon be reading "all" files under a zip downloaded. But we are not there yet. They both use `list.files`.
3. As for the multi-read, for the sake of getting the package out sooner and I discussed this with Robin, I think there is a 3rd option: leave it for versions post CRAN.
4. As for changing file names, I think it is safer to keep the source structure intact hence my initial scraping of the 52 file names from DfT. But that is definitely one option, again, I suggest we keep it for post CRAN.

Happy to go with agreed paths forward.

**Comment by layik** [comment]
extra warnings for the 1.8 GB resulting file, code stolen from `crayon` 📦 

<img width="609" alt="screenshot 2018-12-03 at 20 56 31" src="https://user-images.githubusercontent.com/408568/49401059-01800400-f73e-11e8-8d81-1e946bd18d74.png">

**Comment by layik** [comment]
https://github.com/ITSLeeds/stats19/commit/14e9919abd7ea5a140e44ae8842d214609d291e7

**Comment by Robinlovelace** [comment]
Very nice!

**Comment by layik** [comment]
#26 :)
