### ISSUE TITLE
Use R.cache

### ISSUE THREAD

**Issue by mpadge** [ITSLeeds/stats19#22]
The data are delivered by Amazon S3, so over-burdening the server should never be an issue, but nevertheless as the [1974-2004 data](#21) are in a single 240MB file, it might be useful to invisibly cache previous calls using the [`R.cache` pacakge](https://github.com/HenrikBengtsson/R.cache).

Note, however, that that beast unpacks to:

file | size
--- | ---
Accidents | 755 MB
Causalty | 360 MB
Vehicles | 721 MB
Total | 1.8GB

Caching that monster might be asking a bit too much?

**Comment by layik** [comment]
Grateful you did the "table" work @mpadge. I agree, caching that beast should not be at least today's priority. See how best I can handle 1974-2004, I can think of a `dl_stats19_1974-2004` or a name like that and `dl_stats19` can just call the function if passed such years.

**Comment by layik** [comment]
See if I can get in some proper `doc` in there and if need be, refer to this issue within the code.

**Comment by Robinlovelace** [comment]
@mpadge are those sizes as csvs? I thought about caching and think there may be advantages of adding it as an argument. Would that mean the data is persistent from one session to the next? The issue currently is that `tempdir()` constantly changes where the files are downloaded to. Thanks for looking into it.

**Comment by mpadge** [comment]
`R.cache` uses a "default" directory of `~/.Rcache`, which is not really default because it's the only option that works between sessions. But then yes, it is permanent and held between sessions. This is also really easy to implement in internal code rather than an extra dep on `R.cache`. And actually, file stats can't be checked without downloading anyway, so `R.cache` would be kinda redundant here, and internal code would be able to do a better job. Let me know and I'll happily PR the concept.

**Comment by Robinlovelace** [comment]
Great - I think that answers my previous question! Thanks and I guess the answer is 'not for now' so closing but happy to re-open pending updated info from you and Layik.
