### ISSUE TITLE
Remove readline call

### ISSUE THREAD

**Issue by mpadge** [ITSLeeds/stats19#26]
I like a good `readline` as much as anyone, but these have the one very undesirable effect of preventing any functions using that from being scripted. These downloads really are very small, so I suggest it will likely be more convenient for users of the package if `readline` were removed.

I had a bit more `readline` stuff in earlier versions of `bikedata`, but have ultimately reduced it to a single usage for instances where people try to download **everything**. This issues some kind of warning about the result being > 500GB or so, but anything smaller than that I just let go.

Just a suggestion.

**Comment by layik** [comment]
I think the secret sauce thing may have a say in here. One for private conversations.

**Comment by Robinlovelace** [comment]
**stats19** is mostly designed to be used interactively and you can always skip those parts if

``` r
!interactive()
#> [1] TRUE
```

<sup>Created on 2018-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Just been looking at **devtools** [code](https://github.com/r-lib/devtools/blob/5ca45ef3d0272505ef153b9644a0ca24f4126323/R/utils.R#L105), as that package has lots of useful interactivity. Seems that it uses `utils::menu()`. That could be a slight improvement on `readline()`.

When there are multiple options to choose from interactivity is useful. Setting `if(!interactive()) { don't do interactive stuff }` is my suggested solution for the rare occasions `dl_stats19()` is used non-interactively (e.g. in the vignette).
