### ISSUE TITLE
Decide on and document api (function names)

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/stats19#3]

**Comment by Robinlovelace** [comment]
- One `dl_stats19()` that has `years` (2010:2013) and `type` (accident) parameter that calls pre-existing code (e.g. in `stats19::dl_stats19_2005_2014` - write new code)
- `read_crashes()`, `read_vehicles()` `read_casualties()` - with `years` 
- `format_stats19()` - behind the scenes for cleaning-up different files.

**Comment by Robinlovelace** [comment]
Closing as decided now. I think there should be another function type: `get_*()` which does all those things, e.g. `get_accidents()` which gets accident tables (which are enough for maybe 75% of analysis) and `get_stats19()`, a master function which gets them all *and* joins them.

**Comment by layik** [comment]
I think we should discuss this in light of the `find_file_name`s and the strategy forward including #11

**Comment by layik** [comment]
I can see the point of these

> read_crashes(), read_vehicles() read_casualties() - with years

Will add `read_accidents` (not crashes as agreed) and check here for the way forward.

**Comment by layik** [comment]
So currently we do have `read_accidents` but it relies on a dir and file_name to read and it does the "formatting" in place @mem48? Are we changing all this @Robinlovelace to your `format_stats19` function?

**Comment by layik** [comment]
No it does not do formatting in place.
Will create a ticket to clear/improve `read_stats19.R`

**Comment by Robinlovelace** [comment]
Thanks for looking into this Layik. One to discuss I think...

**Comment by layik** [comment]
:rocket:
