### ISSUE TITLE
Make it easy to skip tests involving downloading data

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/stats19#32]
This could be useful if you want to run the tests quickly, or if you have slow internet. Sure it's possible, not sure how though...

**Comment by layik** [comment]
@Robinlovelace there is the stop_download function, it just needs a variable in your `.Renviron` file

**Comment by layik** [comment]
`usethis::edit_r_environ()`

then add

`DONT_DOWNLOAD_ANYTHING = true`

**Comment by Robinlovelace** [comment]
That's awesome! I just did this and the tests completed much quicker (~1 minute):

```
Sys.setenv(DONT_DOWNLOAD_ANYTHING = "true")
```
