### ISSUE TITLE
2004 to 2008

### ISSUE THREAD

**Issue by layik** [ITSLeeds/stats19#33]
Just wanted to add this issue for people who may land on here searching. I think, as of today, the dft does not publish individual yearly files for 2005-2008, the only file is the overlapping `Stats19_Data_2005-2014.zip`

``` r
stats19::find_file_name(years = 2005)
#> [1] "Stats19_Data_2005-2014.zip"
stats19::find_file_name(years = 2006)
#> character(0)
stats19::find_file_name(years = 2007)
#> character(0)
stats19::find_file_name(years = 2008)
#> [1] "MakeModel2004_2008.zip"
```

<sup>Created on 2018-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Correct?

Note: we would need to cater for this in the package, like we do or were doing for 1979-2004.

**Comment by Robinlovelace** [comment]
Thanks for passing that on. I am thinking of a solution: do it in the function `check_year()`. Sound like a good plan @layik ?

**Comment by layik** [comment]
the 1979-2004 "semantic" fix was done elsewhere:
https://github.com/ITSLeeds/stats19/blob/layik/R/utils.R#L53

It could be done there, but I think there a deeper issue with the rewrite which needs to be fixed first. I am sorry Robin, I will focus on the private.

**Comment by Robinlovelace** [comment]
Thanks @layik, make sense. I think the problem is no longer with `find_file_names()` - see reprex below - but with one of the other changes (e.g. `get_url()`) functions added by @mpadge.

``` r
library(stats19)
#> Data provided under the conditions of the Open Government License.
#> If you use data from this package, mention the source
#> (Department for Transport), cite the package and link to:
#> www.nationalarchives.gov.uk/doc/open-government-licence/version/3/.
find_file_name(1985)
#> [1] "Stats19-Data1979-2004.zip"
```

<sup>Created on 2018-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by layik** [comment]
fixed
