### ISSUE TITLE
geolocate_casualties/vehicles functions

### ISSUE THREAD

**Issue by mpadge** [ITSLeeds/stats19#56]
Quoting @Robinlovelace from slack:
>  merging of the tables is non trivial. It has made my head explode on at least 3 occasions.
A post-CRAN idea is to add 'idiot-proof' custom join functions (it's easy to bork). Any ideas on that, if you look at merging in the vignette, building on the join example I added to the readme, would be grately appreciated.

I agree with @layik's subsequent:
> Warning: https://en.wikipedia.org/wiki/Mission_creep

.. and accordingly suggest one simple function that does the table joins and nothing else. I think we may safely presume that primary use case for table joins is going to be to geolocate the two tables that do not have this info: casualties and vehicles. Suggestion in thus:
```
stats19_geolocate(tab1, tab_crashes)
```
where `tab1` can - **must** - be either `casualties` or `vehicles`, and the result will be a `left_join` to `tab1` to `tab_crashes`. Thoughts?

**Comment by Robinlovelace** [comment]
This is mission creep for now. Can re-open when we've had more feedback from others and had a chance to think about +s and -s.
