### ISSUE TITLE
vignette

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/stats19#8]

**Comment by layik** [comment]
I will see if I can learn something from `osmdata` or `stplanr` to have a go at this!

**Comment by layik** [comment]
https://github.com/ITSLeeds/stats19/commit/4ee848ac9188f79b84b2ef03ced8e835ecc4cf8e

At least bullet points but definitely few sections which are best written by @Robinlovelace.

**Comment by layik** [comment]
Over to you @Robinlovelace for submission to CRAN.
